services:
    php:
        build:
            context: .
            dockerfile: docker/php/Dockerfile
            args:
                TIMEZONE: ${TIMEZONE}
        container_name: viajespt_php
        volumes:
            - .:/var/www/viajespt/
        networks:
            - ViajesParaTi

    nginx:
        build:
            context: .
            dockerfile: docker/nginx/Dockerfile
        container_name: viajespt_nginx
        volumes:
            - .:/var/www/viajespt/
        ports:
            - 80:80
        networks:
            - ViajesParaTi

    db:
        container_name: viajespt_db
        image: mysql:8.0
        ports:
            - 3310:3306
        environment:
            MYSQL_DATABASE: proveedores
            MYSQL_USER: user
            MYSQL_PASSWORD: viajespt
            MYSQL_ROOT_PASSWORD: viajesptroot
        command: mysqld --sql_mode="STRICT_ALL_TABLES,NO_ENGINE_SUBSTITUTION"
        volumes:
            - .:/var/www/viajespt/
        networks:
            - ViajesParaTi
networks:
    ViajesParaTi: